name: A workflow for my Hello World file
on: 
  create

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
      - name: Print github data
        run: |
          echo $github
        
